services:
  trino:
    hostname: dbt_test
    container_name: dbt_trino
    image: dbt_trino:testing
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount your local project directory to container
      # - ./:/usr/app/dbt_project
      # Mount dbt profiles for persistence
      - ../dbt-trino-template/profiles:/root/.dbt
      #auto mount dbt script from host to container
      - ../dbt-trino-template/models:/usr/app/dbt/raffle_shop/models
      - ../dbt-trino-template/seeds:/usr/app/dbt/raffle_shop/seeds
      - ../dbt-trino-template/macros:/usr/app/dbt/raffle_shop/macros
      #- ./models:/usr/app/dbt/raffle_shop/models
    ports:
      # Map container port to host
      - "5180:5000"
    networks:
      network_test:
        ipv4_address: 172.18.0.5
    environment:
      # set environment variables
      - DBT_PROFILES_DIR=/root/.dbt
      - OPENLINEAGE_URL=http://marquez-api:5000
      - OPENLINEAGE_NAMESPACE=dev
      - OPENLINEAGE_DBTRUNNER_TRACER=custom_dbt_tracer.CustomDbtTracer
    # Keep container running
    tty: true
    stdin_open: true
    command: bash
    # Optional: Restart policy
    restart: unless-stopped
networks:
  network_test:
    name: network_test
    external: true
